export const tweetsData = [
  {
    handle: `@TrollBot66756542 💎`,
    username: "The Blonde",
    profilePic: `images/troll.jpg`,
    likes: 27,
    retweets: 10,
    tweetText: `Buying Tom Cruise photo at any prices 💰💰💰. 
            Dm me anytimes !!`,
    replies: [],
    isLiked: false,
    isRetweeted: false,
    uuid: "4b161eee-c0f5-4545-9c4b-8562944223ee",
    date: "3:47 AM Feb 9, 2023",
  },
  {
    handle: `@Elon`,
    username: "Elon Musk",
    profilePic: `images/musk.png`,
    likes: 6500,
    retweets: 234,
    tweetText: `I need volunteers for a one-way mission to Mars 🪐. No experience necessary🚀`,
    replies: [
      {
        handle: `@T.Cruise`,
        username: "Tom Cruise",
        profilePic: `images/tcruise.png`,
        tweetText: `Yes! Sign me up! 😎🛩`,
        date: "Feb 19",
        replyCase: 1,
        replyTo: "@ELon",
      },
      {
        handle: `@ElBlonde`,
        username: "The Blonde",
        profilePic: `images/troll.jpg`,
        tweetText: `Tom I am your most retarded fan !`,
        date: "Feb 19",
        replyCase: 2,
        replyTo: "@T.cruise",
      },
      {
        handle: `@Ch.Norris`,
        username: "Chucky",
        profilePic: `images/chucknorris.jpeg`,
        tweetText: `I still have a bullet left in my gun`,
        date: "Apr 25",
        replyCase: 3,
        replyTo: "@ElBlonde",
      },
      {
        handle: `@Scrimba`,
        username: "Scrimba",
        profilePic: `images/scrimbalogo.png`,
        tweetText: `I have a few student specimen for your project !`,
        date: "Feb 25",
        replyCase: 4,
        replyTo: "@ELon",
      },
    ],
    isLiked: false,
    isRetweeted: false,
    uuid: "3c23454ee-c0f5-9g9g-9c4b-77835tgs2",
    date: "5:47 AM Feb 16, 2023",
  },
  {
    handle: `@NoobPlayer12`,
    username: "Noob player",
    profilePic: `images/flower.png`,
    likes: 10,
    retweets: 3,
    tweetText: `Are you a feeder if you die 5 times in a minute ?`,
    replies: [
      {
        handle: `@St.Overflow`,
        username: "TheStack",
        profilePic: `images/overflow.png`,
        tweetText: `Yes you are ! Go get a job in McDonald's.`,
        date: "Oct 01",
        replyCase: 1,
        replyTo: "@NoobCoder12",
      },
      {
        handle: `@YummyCoder64`,
        username: "Love",
        profilePic: `images/love.png`,
        tweetText: `It's only game why you have to be mad ❤️`,
        date: "Dec 24",
        replyCase: 3,
        replyTo: "@StackOverflow",
      },
    ],
    isLiked: false,
    isRetweeted: false,
    uuid: "8hy671sff-c0f5-4545-9c4b-1237gyys45",
    date: "3:47 PM Feb 25, 2023",
  },
];
